const mongoose = require('mongoose')
const comentarioSchema = new mongoose.Schema({
  texto: { type: String},
  fecha: { type: String },
  usuario: {type: String},
  hora: {type: String}
})

const casoSchema = new mongoose.Schema({
  numero: { type: String},
  codigo: { type: String},
  titulo: { type: String },
  cliente: { type: mongoose.Schema.Types.ObjectId, ref: 'Cliente' },
  asunto: { type: String },
  area: { type: String },
  fechaDeAsignacion: { type: String },
  centroDeTrabajo: { type: String },
  directorACargo: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  abogadoACargo: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  abogadoInternoDeLaCompania: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  siniestro: { type: mongoose.Schema.Types.ObjectId, ref: 'Siniestro' },
  fechaSiniestro: { type: String },
  poliza: { type: String },
  ramo: { type: String},
  amparo: { type: String },
  numeroAplicativo: { type: String },
  ciudad: { type: String },
  juzgadoInt: { type: mongoose.Schema.Types.ObjectId, ref: 'Juzgado' },
  radicado: {type: String},
  parteActiva: { type: String },
  partePasiva: { type: String },
  tipoDeTramite: { type: String },
  claseDeProceso: { type: String },
  tipoDeVinculacionCliente: { type: String },
  pretensionesEnDinero: { type: String },
  calificacionInicialContingencia: { type: String },
  calificacionActualContingencia: { type: String },
  motivoDeLaCalificacion: { type: String },
  fechaAdmisionVinculacion: { type: String },
  fechaDeNotificacion: { type: String },
  instancia: { type: String },
  etapaProcesal: { type: String },
  claseDeMedidaCautelar: { type: String },
  honorariosAsignados: { type: String },
  autoridadDeConocimiento: { type: String },
  delito: { type: String },
  placa: { type: String },
  evento: { type: String },
  probabilidadDeExito: { type: String },
  valorIndemnizadoCliente: { type: String },
  entidadAfectada: { type: String },
  fechaDePagoCliente: { type: String },
  tipoContragarantia: { type: String },
  montoDeProvision: { type: String },
  tipoDeMoneda: { type: String },
  fechaDeTerminacion: { type: String },
  motivoDeTerminacion: { type: String },
  cliente2: { type: mongoose.Schema.Types.ObjectId, ref: 'Cliente' },
  fechaDeAsignacion2: { type: String },
  abogadoInternoDeLaCompania2: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  siniestro2: { type: mongoose.Schema.Types.ObjectId, ref: 'Siniestro' },
  numeroDeAplicativo2: { type: String },
  fechaDeNotificacion2: { type: String },
  seInicioEjecutivoAContinuacionDeOrdinario: { type: String },
  honorariosAsignados2: { type: String },
  valorPagado: { type: String },
  personaQueRealizoElPago: { type: String },
  fechaDeRadicacionDeLaContestacion: { type: String },
  fechaDeRadicacionDeLaContestacion2: { type: String },
  departamento: { type: String },
  asegurado: { type: String },
  jurisdiccion: { type: String },
  juzgado: { type: mongoose.Schema.Types.ObjectId, ref: 'Juzgado' },
  fechaUltimaActuacion: { type: String },
  tituloUltimaActuacion: { type: String },
  fechaQueRealizoElPago: { type: String },
  codigoInterno: { type: String },
  comentarios: [comentarioSchema]
})

module.exports = mongoose.model('Caso', casoSchema)
