const mongoose = require('mongoose')

const casoSchema = new mongoose.Schema({
  numero: { type: String},
  codigo: { type: String},
  titulo: { type: String },
  cliente: { type: mongoose.Schema.Types.ObjectId, ref: 'Cliente' },
  asunto: { type: String },
  creacion: { type: Date },
  ubicacionDelExpediente: { type: String },
  codigoInterno: { type: String },
  area: { type: String },
  fechaDeAsignacion: { type: Date },
  centroDeTrabajo: { type: String },
  directorACargo: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  abogadoACargo: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  abogadoInternoDeLaCompania: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  siniestro: { type: mongoose.Schema.Types.ObjectId, ref: 'Siniestro' },
  fechaSiniestro: { type: Date },
  poliza: { type: String },
  ramo: { type: String},
  amparo: { type: String },
  numeroAplicativo: { type: String },
  ciudad: { type: String },
  juzgadoInt: { type: mongoose.Schema.Types.ObjectId, ref: 'Juzgado' },
  radicado: {type: String},
  parteActiva: { type: String },
  partePasiva: { type: String },
  tipoDeTramite: { type: String },
  claseDeProceso: { type: String },
  tipoDeVinculacionCliente: { type: String },
  pretensionesEnDinero: { type: Number },
  calificacionInicialContingencia: { type: String },
  calificacionActualContingencia: { type: String },
  motivoDeLaCalificacion: { type: String },
  fechaAdmisionVinculacion: { type: Date },
  fechaDeNotificacion: { type: Date },
  instancia: { type: String },
  etapaProcesal: { type: String },
  claseDeMedidaCautelar: { type: String },
  honorariosAsignados: { type: Number },
  autoridadDeConocimiento: { type: String },
  delito: { type: String },
  placa: { type: String },
  evento: { type: String },
  probabilidadDeExito: { type: String },
  valorIndemnizadoCliente: { type: Number },
  entidadAfectada: { type: String },
  fechaDePagoCliente: { type: Date },
  tipoContragarantia: { type: String },
  montoDeProvision: { type: Number },
  tipoDeMoneda: { type: String },
  fechaDeTerminacion: { type: Date },
  motivoDeTerminacion: { type: String },
  cliente2: { type: mongoose.Schema.Types.ObjectId, ref: 'Cliente' },
  fechaDeAsignacion2: { type: Date },
  abogadoInternoDeLaCompania2: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  siniestro2: { type: mongoose.Schema.Types.ObjectId, ref: 'Siniestro' },
  numeroDeAplicativo2: { type: String },
  fechaDeNotificacion2: { type: Date },
  seInicioEjecutivoAContinuacionDeOrdinario: { type: Boolean },
  honorariosAsignados2: { type: Number },
  valorPagado: { type: Number },
  personaQueRealizoElPago: { type: String },
  fechaDeRadicacionDeLaContestacion: { type: Date },
  fechaDeRadicacionDeLaContestacion2: { type: Date },
  departamento: { type: String },
  asegurado: { type: String },
  jurisdiccion: { type: String },
  materia: { type: String },
  detalleDeMateria: { type: String },
  estado: { type: String },
  estadoInterno: { type: String },
  juzgado: { type: mongoose.Schema.Types.ObjectId, ref: 'Juzgado' },
  moneda: { type: String },
  cuantia: { type: Number },
  contingenciaReal: { type: Number },
  provision: { type: Number },
  condenaArreglo: { type: Number },
  totalComisiones: { type: Number },
  totalRecaudacion: { type: Number },
  totalGastos: { type: Number },
  fechaInicio: { type: Date },
  fechaTermino: { type: Date },
  flujoDeTrabajo: { type: String },
  etapaDeFlujo: { type: String },
  primeraParteActiva: { type: String },
  primeraPartePasiva: { type: String },
  usuariosInvolucrados: {type: String },
  ultimaTareaFinalizada: { type: String },
  fechaUltimaActuacion: { type: Date },
  tituloUltimaActuacion: { type: String },
  fechaUltimoCambioDeEstado: { type: Date },
  usuarioCreador: { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario' },
  notificado: { type: String },
  cartera: { type: String },
  numeroCredencial: { type: String },
  usuarioCredencial: { type: String },
  rutCredencial: { type: String },
})

module.exports = mongoose.model('Caso', casoSchema)
